FinalProject.WebApp/Areas/Admin/Controllers/ProductController.cs
using FinalProject.Entities.DTOs;
using FinalProject.Services.Contracts;
using FinalProject.Services.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalProject.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            return View(_manager.ProductService.GetAllProducts(true).GetProductsByDescendingDate());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = GetCategoriesSelectList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductCreateDTO model, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //File Operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                model.ImageUrl = file.FileName;
                _manager.ProductService.CreateOneProduct(model);
                TempData["Success"] = $"{model.Name} adlı ürün başarılı bir şekilde eklenmiştir.";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductDTO(id, false);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ProductCreateDTO model, IFormFile? file)
        {
            if (file is not null)
            {
                //File Operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                model.ImageUrl = file.FileName;
            }

            _manager.ProductService.UpdateOneProduct(model);
            TempData["Success"] = $"{model.Name} adlı ürün başarılı bir şekilde güncllenmiştir.";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        { 
            _manager.ProductService.DeleteOneProduct(id);
            return RedirectToAction("Index");
        }

        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetCategories(true), "Id", "Name");
        }
    }
}

FinalProject.WebApp/Components/CategoryMenuViewComponent.cs
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoryMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke() 
        {
            var categoryWithCountDTOs = _manager.CategoryService.GetCategoriesWithCount();
            return View(categoryWithCountDTOs);
        }
    }
}

FinalProject.WebApp/Controllers/ProductController.cs
using FinalProject.Entities.Enums;
using FinalProject.Entities.Request;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using FinalProject.Services.Extensions;

namespace FinalProject.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(RequestParameters param)
        {
            var products = _manager.ProductService.GetAllProductDTOs(false, Status.Active);    
            
            if(param.CatId != null)
                products = products.ByCatId(param.CatId);
            
            if (param.search != null)
                products = products.BySearch(param.search);

            if(param.MinPrice != null && param.MaxPrice != null && param.IsValidPrice)
                products = products.ByPrice(param.MinPrice, param.MaxPrice);

            return View(products);
        }

        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _manager.ProductService.GetOneProductDTO(id, false);
            if(model is not null)
                return View(model);
            return RedirectToPage("/Error");
        }
    }
}

FinalProject.WebApp/Views/Product/GetById.cshtml
@model ProductCreateDTO
@{
    ViewData["Title"] = Model.Name;
}

<div class="row">
    <div class="col-md-3">
        <div class="text-center">
            <img class="img-fluid shadow rounded-3 my-3" src="~/images/@Model.ImageUrl" />
        </div>
    </div>
    <div class="col-md-9">
        <div class="text-start">
            <h3 class="my-1 display-4">@Model.Name</h3>
            <p class="lead text-danger">
                <b>Price: </b>@Model.Price.ToString("C2")
            </p>
            <form id="@Model.Id" asp-page="/Error2" method="post">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-outline-success">
                    <i class="fa fa-cart-plus"></i> Add Basket
                </button>
            </form>
        </div>
    </div>
</div>
<div class="row border-top py-3 my-3">
    <div class="col-md-12">
        <h4 class="my-1 display-6">Summary</h4>
        <div class="px-3 my-3">
            @Html.Raw(Model.Summary)
        </div>
    </div>
</div>

FinalProject.WebApp/Views/Product/Index.cshtml
@model IEnumerable<ProductDTO>

@{
    ViewData["Title"] = "All Products";
}

<h2>Products </h2>
<hr />
<div class="row">
    <div class="col-md-3">
        <h3>Kategoriler</h3>
        <hr />
        @await Component.InvokeAsync("CategoryMenu")
        
        <div class="my-3">
            <h4>Fiyat Filitresi</h4>
            <form asp-action="" method="get">
                <div>
                    <input name="MinPrice" class="form-text" placeholder="Minimum Fiyat" />
                </div>
                <div>
                    <input name="MaxPrice" class="form-text" placeholder="Maksimum Fiyat" />
                </div>
                <div>
                    <button type="submit" class="btn btn-success">Uygula</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-9">
        <div class="row">
            @if (Model is not null && Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    @await Html.PartialAsync("_ProductCard",item)
                }
            }
            else
            {
                <div class="alert alert-warning" role="alert">
                    Bu kategoride sizlere gösterebileceğimiz bir ürün bulunmamaktadır.
                </div>
            }
        </div>
    </div>
</div>