FinalProject.WebApp/Areas/Admin/Controllers/CategoryController.cs
using FinalProject.Entities.DTOs;
using FinalProject.Entities.Enums;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            return View(_manager.CategoryService.GetCategories(true));
        }

        [HttpGet]
        public IActionResult Create()
        { 
            return View();
        }

        [HttpPost]
        public IActionResult Create(string CategoryName)
        {
            _manager.CategoryService.CreateCategory(CategoryName);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            return View(_manager.CategoryService.GetCategoryDTOById(id));
        }

        [HttpPost]
        public IActionResult Edit(CategoryDTO model, string durum) 
        {
            model.Status = durum != null ? Status.Active : Status.Passive;
            _manager.CategoryService.UpdateCategory(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id) 
        {
            _manager.CategoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }
    }
}

FinalProject.WebApp/Components/ProductCountViewComponent.cs
using FinalProject.Entities.Enums;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Components
{
    public class ProductCountViewComponent : ViewComponent
    {
        private readonly IServiceManager _manger;

        public ProductCountViewComponent(IServiceManager manger)
        {
            _manger = manger;
        }

        public string Invoke()
        {
            return _manger.ProductService.GetAllProducts(false, Status.Active).Count().ToString();
        }
    }
}

FinalProject.WebApp/Controllers/OrderController.cs
using FinalProject.Entities.Models;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly Cart _cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _serviceManager = serviceManager;
            _cart = cart;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (_cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Üzgünüz sepetiniz boş");

            if (ModelState.IsValid) 
            { 
                order.Lines = _cart.Lines;
                order.UserId = _serviceManager.UserManager.GetUserId(User);
                _serviceManager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToAction("Complete", new { OrderId = order.Id });
            }
            return View(order);
        }

        [HttpGet]
        public IActionResult Complete(int OrderId) 
        { 
            var order =  _serviceManager.OrderService.GetOneOrder(OrderId);
            ViewData["Success"] = "Tebrikler şiparişini başarılı bir şekilde oluştu.";
            return View(order);
        }

        [HttpGet]
        public IActionResult MyOrders() 
        {
            var userId = _serviceManager.UserManager.GetUserId(User);
            var myOrders = _serviceManager.OrderService.GetAllOrdersByUserId(userId);
            return View(myOrders);
        }
    }
}

FinalProject.WebApp/Controllers/ProductController.cs
using FinalProject.Entities.Enums;
using FinalProject.Entities.Request;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using FinalProject.Services.Extensions;

namespace FinalProject.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(RequestParameters param)
        {
            var products = _manager.ProductService.GetAllProductDTOs(false, Status.Active);    
            
            if(param.CatId != null)
                products = products.ByCatId(param.CatId);
            
            if (param.search != null)
                products = products.BySearch(param.search);

            if(param.MinPrice != null && param.MaxPrice != null && param.IsValidPrice)
                products = products.ByPrice(param.MinPrice, param.MaxPrice);

            return View(products);
        }

        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _manager.ProductService.GetOneProductDTO(id, false);
            if(model is not null)
                return View(model);
            return RedirectToPage("/Error");
        }
    }
}

FinalProject.WebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KD-24 Store Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.WebApp.styles.css" asp-append-version="true" />
    @RenderSection("NewCss",false)
</head>
<body>
    <header>
        <nav class="navbar bg-dark navbar-expand-lg navbar-toggleable-lg box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">KD-24 Store Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Product" asp-action="Index">Products <span class="text-success">(@await Component.InvokeAsync("ProductCount"))</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                    <div class="navbar-nav" style="margin-right:30px;">
                        <li class="nav-item">
                            <a class="nav-link text-white" target="_blank" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-arrow-circle-o-up"></i> Web</a>
                        </li>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FinalProject.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>