FinalProject.WebApp/Components/CardSummaryViewComponent.cs
using FinalProject.Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Components
{
    public class CardSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CardSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public string Invoke()
        {
            return _cart.Lines.Count.ToString();
        }
    }
}

FinalProject.WebApp/Components/ProductCountViewComponent.cs
using FinalProject.Entities.Enums;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Components
{
    public class ProductCountViewComponent : ViewComponent
    {
        private readonly IServiceManager _manger;

        public ProductCountViewComponent(IServiceManager manger)
        {
            _manger = manger;
        }

        public string Invoke()
        {
            return _manger.ProductService.GetAllProducts(false, Status.Active).Count().ToString();
        }
    }
}

FinalProject.WebApp/Controllers/OrderController.cs
using FinalProject.Entities.Models;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly Cart _cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _serviceManager = serviceManager;
            _cart = cart;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (_cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Üzgünüz sepetiniz boş");

            if (ModelState.IsValid) 
            { 
                order.Lines = _cart.Lines;
                order.UserId = _serviceManager.UserManager.GetUserId(User);
                _serviceManager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToAction("Complete", new { OrderId = order.Id });
            }
            return View(order);
        }

        [HttpGet]
        public IActionResult Complete(int OrderId) 
        { 
            var order =  _serviceManager.OrderService.GetOneOrder(OrderId);
            ViewData["Success"] = "Tebrikler şiparişini başarılı bir şekilde oluştu.";
            return View(order);
        }

        [HttpGet]
        public IActionResult MyOrders() 
        {
            var userId = _serviceManager.UserManager.GetUserId(User);
            var myOrders = _serviceManager.OrderService.GetAllOrdersByUserId(userId);
            return View(myOrders);
        }
    }
}

FinalProject.WebApp/Controllers/ProductController.cs
using FinalProject.Entities.Enums;
using FinalProject.Entities.Request;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using FinalProject.Services.Extensions;

namespace FinalProject.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(RequestParameters param)
        {
            var products = _manager.ProductService.GetAllProductDTOs(false, Status.Active);    
            
            if(param.CatId != null)
                products = products.ByCatId(param.CatId);
            
            if (param.search != null)
                products = products.BySearch(param.search);

            if(param.MinPrice != null && param.MaxPrice != null && param.IsValidPrice)
                products = products.ByPrice(param.MinPrice, param.MaxPrice);

            return View(products);
        }

        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _manager.ProductService.GetOneProductDTO(id, false);
            if(model is not null)
                return View(model);
            return RedirectToPage("/Error");
        }
    }
}

FinalProject.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KD-24 Store App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KD-24 Store App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products <span class="text-success">(@await Component.InvokeAsync("ProductCount"))</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <div class="navbar-nav" style="margin-right:20px;">
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-page="/Error2"><i class="fa fa-cart-shopping"></i> Basket (@await Component.InvokeAsync("CardSummary"))</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" target="_blank" asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="fa fa-edit"></i> Admin</a>
                        </li>
                    </div>
                    <div class="navbar-nav d-flex" style="margin-right:20px;">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Account" asp-action="MyAccount" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user"></i> My Account (@User.Identity.Name)
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-action="MyOrders" asp-controller="Order">Siparişlerim</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa fa-user-astronaut"></i> Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register"><i class="fa fa-user-plus"></i> Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa fa-user-check"></i> Login</a>
                            </li>
                        }

                    </div>
                    <form method="get" asp-controller="Product" asp-action="Index" class="d-flex" role="search">
                        <input type="hidden" name="CatId" value="@Context.Request.Query["CatId"]" />
                        
                        <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FinalProject.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinalProject.WebApp/Views/Shared/_ProductCard.cshtml
@model ProductDTO

<div class="col-sm-12 col-md-4 my-2">
    <div class="card" style="width: 18rem;">
        <img src="~/images/@Model.ImageUrl" class="card-img-top" alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text"><b>Price: </b>@Model.Price.ToString("C2")</p>
            <div class="btn btn-group">
                <a asp-controller="Product" asp-action="GetById" asp-route-id="@Model.Id" class="btn btn-success"><i class="fa fa-arrow-right"></i> Detail</a>
                <form id="@Model.Id" asp-page="/Error2" method="post" >
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-outline-success">
                        <i class="fa fa-cart-plus"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>