FinalProject.WebApp/Controllers/OrderController.cs
using FinalProject.Entities.Models;
using FinalProject.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.WebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly Cart _cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _serviceManager = serviceManager;
            _cart = cart;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (_cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Üzgünüz sepetiniz boş");

            if (ModelState.IsValid) 
            { 
                order.Lines = _cart.Lines;
                order.UserId = _serviceManager.UserManager.GetUserId(User);
                _serviceManager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToAction("Complete", new { OrderId = order.Id });
            }
            return View(order);
        }

        [HttpGet]
        public IActionResult Complete(int OrderId) 
        { 
            var order =  _serviceManager.OrderService.GetOneOrder(OrderId);
            ViewData["Success"] = "Tebrikler şiparişini başarılı bir şekilde oluştu.";
            return View(order);
        }

        [HttpGet]
        public IActionResult MyOrders() 
        {
            var userId = _serviceManager.UserManager.GetUserId(User);
            var myOrders = _serviceManager.OrderService.GetAllOrdersByUserId(userId);
            return View(myOrders);
        }
    }
}

FinalProject.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FinalProject.WebApp.Pages
{
    public class ErrorModel : PageModel
    {

        public void OnGet()
        {

        }

    }
}

FinalProject.WebApp/Pages/Error2.cshtml.cs
using FinalProject.Entities.DTOs;
using FinalProject.Entities.Models;
using FinalProject.Services.Contracts;
using FinalProject.WebApp.Infrastructe.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FinalProject.WebApp.Pages
{
    public class ErrorModel2 : PageModel
    {
        private readonly IServiceManager _manager;

        public ErrorModel2(IServiceManager manager, Cart cart)
        {
            _manager = manager;
            Cart = cart;
        }

        public void OnGet()
        {
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }
        public Cart Cart { get; set; }
        public IActionResult OnPost(int Id)
        {
            ProductCreateDTO? product = _manager.ProductService.GetOneProductDTO(Id, false);

            if (product is not null)
            {
                Cart.AddItem(product, 1);
            }
            HttpContext.Session.SetJson<Cart>("cart", Cart);
            return RedirectToPage("/Error2");
        }

        public IActionResult OnPostRemove(int id)
        {
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            //Cart.RemoveItem(Cart.Lines.First(cl => cl.Product.Id == id).Product);
            //HttpContext.Session.SetJson<Cart>("cart", Cart);
            return Page();
        }
    }
}

FinalProject.WebApp/Pages/Error2.cshtml
@page
@{
    Layout = "_Layout";
}
@model FinalProject.WebApp.Pages.ErrorModel2
@{
}

<div>
    <div class="text-center display-6">
        My Basket
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    SubTotal
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart?.Lines)
            {
                <tr>
                    <td>
                        @line.Product.Name
                    </td>
                    <td>
                        @line.Quantity
                    </td>
                    <td>
                        @((line.Product.Price * line.Quantity).ToString("C2"))
                    </td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.Id" />
                            <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">
                    Total :
                </td>
                <td>
                    @Model.Cart?.TotalPrice().ToString("C2")
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
            Checkout
        </a>
    </div>
</div>